# Generated by Django 5.2 on 2025-07-27 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='last_name',
        ),
    ]
