# Generated by Django 5.2.4 on 2025-07-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_car_brand'),
        ('main', '0002_car_description_alter_car_name_carimage'),
    ]

    operations = [
    ]
