# Generated by Django 5.2.4 on 2025-07-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_car_description_alter_car_name_delete_carimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.AddField(
            model_name='car',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/back/'),
        ),
        migrations.AddField(
            model_name='car',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/front/'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_3d_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Ford', 'Ford'), ('BMW', 'BMW'), ('Mercedes', 'Mercedes')], max_length=100),
        ),
    ]
