# Generated by Django 5.2.4 on 2025-07-24 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_car_image_car_back_image_car_front_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='main.car')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
