# Generated by Django 5.2.4 on 2025-07-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_car_back_image_alter_car_front_image_carimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='image',
        ),
        migrations.AddField(
            model_name='carimage',
            name='image_url',
            field=models.URLField(default=12, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
