# Generated by Django 5.2 on 2025-07-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_carimage_image_carimage_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='carimage',
            name='image',
            field=models.ImageField(default='exit', upload_to='cars/gallery/'),
            preserve_default=False,
        ),
    ]
