# Generated by Django 5.2 on 2025-07-28 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_carimage_image_url_carimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='gallery_images',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='main.carimage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='back_image',
            field=models.ImageField(default='', upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='front_image',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images1', to='main.car'),
        ),
    ]
